services:
  nvim:
    build: .
    image: nvim
    command: nvim -u init.lua
    tty: true
    stdin_open: true
    working_dir: /workspace
    volumes:
      - .:/workspace/
      - ./volumes/root/.local/share/nvim/site/pack:/root/.local/share/nvim/site/pack
      - ./volumes/root/.npm:/root/.npm
